### ISSUE TITLE
Write content for website

### ISSUE THREAD

**Issue by AdamVig** [stockpile-co/stockpileapp.co#4]
Write out all website content and send to our designer so she can create a layout.

**Comment by AdamVig** [comment]
*Logo*
Stockpile is the simplest way to manage your inventory. Whether you have video production equipment, theater props, landscaping tools, or all three, Stockpile is the way to go.

*Screenshot of inventory view in front of photo of tagged items*
With Stockpile, you can tag all of your items with barcodes and add them to the inventory. Each item has a brand, model, and category. You can use these fields to filter your inventory, making it easy to find exactly the item you are looking for.

*Animation of renting items*
When you want to rent items, all you have to do is scan them with your camera and select a return date. To return the items, simply scan them again.

*Image of camera with two batteries and bag*
Use Kits to create collections of items that go together: for example, a camera, two batteries, and a camera bag.

*Photo of a team of people*
Stockpile is best when used in organizations. Sign everybody up and have them download the app so that everyone can add items to the inventory, see what items are available, and rent/return items.

All of these great features come at a low price. We charge a flat rate of $20 per month no matter how large your inventory or how large your organization.

**Upcoming Features**
- Item Reservations
- Integration with Calendar Applications

**Comment by emroussel** [comment]
That sounds great! Most of the coming soon features will be implemented in the next few weeks though, so I'm not sure if it is worth including them on there. A notable one that will take longer to do though is being able to reserve items/plan for shoots and the integration with Google Calendar.

I think we should also add pricing there. We should mention that there is one price for everything per organization (any number of user and items) and what the price is.

**Comment by AdamVig** [comment]
Updated to reflect your feedback. Thanks!
